heat_template_version: pike
description: A load-balancer server

parameters:
  network_id:
    type: string
  subnet_id:
    type: string
  pool_id:
    type: string

resources:
  server:
    type: OS::Nova::Server
    properties:
      flavor: m1.small
      image: Ubuntu 16.04 LTS
      key_name: key_duminyj
      user_data: |
        #!/bin/bash
        sudo apt update
        sudo apt install -y nginx
      networks:
        - network: { get_param: network_id }
          subnet: { get_param: subnet_id }

  member:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: {get_param: pool_id}
      address: {get_attr: [server, first_address]}
      protocol_port: 80
      subnet: {get_param: subnet_id}
